name: mastodon_api
description: The easiest and powerful Dart/Flutter library for Mastodon API.
version: 0.0.1
repository: https://github.com/mastodon-dart/mastodon-api
issue_tracker: https://github.com/mastodon-dart/mastodon-api/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5
  universal_io: ^2.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  freezed: ^2.1.1
  import_sorter: ^4.6.0
  mockito: ^5.3.2